name: demo workflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo hi, merion
      - name: print a few line
        run: |
          echo first line 
          echo second line
          echo third line
